/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/ui/accordion.vue')['default']
    AccordionContent: typeof import('./components/ui/AccordionContent.vue')['default']
    AccordionItem: typeof import('./components/ui/AccordionItem.vue')['default']
    AccordionTrigger: typeof import('./components/ui/AccordionTrigger.vue')['default']
    AuthDialog: typeof import('./components/AuthDialog.vue')['default']
    Avatar: typeof import('./components/ui/avatar.vue')['default']
    AvatarFallback: typeof import('./components/ui/AvatarFallback.vue')['default']
    AvatarImage: typeof import('./components/ui/AvatarImage.vue')['default']
    Badge: typeof import('./components/ui/badge.vue')['default']
    Button: typeof import('./components/ui/button.vue')['default']
    Card: typeof import('./components/ui/card.vue')['default']
    CardContent: typeof import('./components/ui/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/CardTitle.vue')['default']
    Dialog: typeof import('./components/ui/dialog.vue')['default']
    DialogContent: typeof import('./components/ui/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/DialogDescription.vue')['default']
    DialogHeader: typeof import('./components/ui/DialogHeader.vue')['default']
    DialogTitle: typeof import('./components/ui/DialogTitle.vue')['default']
    FAQ: typeof import('./components/FAQ.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Input: typeof import('./components/ui/input.vue')['default']
    Label: typeof import('./components/ui/label.vue')['default']
    Packages: typeof import('./components/Packages.vue')['default']
    Separator: typeof import('./components/ui/separator.vue')['default']
    Services: typeof import('./components/Services.vue')['default']
    Tabs: typeof import('./components/ui/tabs.vue')['default']
    TabsContent: typeof import('./components/ui/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/TabsTrigger.vue')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    WhyUs: typeof import('./components/WhyUs.vue')['default']
  }
}
